# Generated by Django 2.1 on 2018-08-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo', max_length=255)),
                ('image', models.ImageField(help_text='imagen', upload_to='images/post')),
                ('content', models.TextField(help_text='Contenido')),
                ('publication_date', models.DateTimeField(help_text='Fecha')),
                ('status', models.BooleanField(default=True, help_text='Estado')),
                ('autor', models.ForeignKey(help_text='Autor', on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['title'],
            },
        ),
    ]
