# Generated by Django 2.1 on 2018-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/author')),
                ('description', models.TextField(help_text='Descripcion')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
    ]
